### PR TITLE
I/5802: Handle clipboard properly in restricte editing mode.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Allow pasting content into exception areas in restricted editing mode. Closes ckeditor/ckeditor5#5802.

---

### Additional information

* I've added a configuration for the text attributes that are allowed inside clipboard holder.

### CODE REVIEW

**Comment by jodator** [comment]
@Mgsy - it's an optimistic approach but should work. Could you check this PR with pasting in Restricted Editing mode? 

- Only configured attributes should be allowed to be pasted (bold, italic, link by default).
- Paste (cut - also) should only occur when selection is fully inside exception.
- Copy should not be blocked.
- Pasting anything other than the text should be stripped down to basic text nodes (or stripped down entirely) - so only text content from tables, no images etc

**Comment by Mgsy** [comment]
@FilipTokarski, please check Chrome and Safari, I'll take Firefox.

**Comment by Mgsy** [comment]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-restricted-editing/tests/manual/restrictedediting.html.
1. Enter the restricted editing mode.
1. Copy some link.
1. Paste it to the exception marker.

## Current result
The plain text is pasted.

## Expected result
The link is pasted.

**Comment by FilipTokarski** [comment]
The same in Chrome and Safari

**Comment by FilipTokarski** [comment]
This https://github.com/ckeditor/ckeditor5/issues/6003 still happens when pasting content into exception marker in a table, BUT i checked https://github.com/ckeditor/ckeditor5-restricted-editing/pull/10 and it seems to be fixing this bug.
So hopefully after 6003 is merged, pasting will work properly too

**Comment by Reinmar** [comment]
Do we need the configuration for allowed attributes? Can't we have all text attributes allowed? Then, if I'm correct, it will be enough to add a callback allowing only `$text` in the `$clipboardHolder`. You won't need the other callback for attribute names. Schema works on the model so we can be very specific here allowing `<$clipboardHolder>$text with all its attributes</$clipboardHolder>` and nothing else. No reason for stuff like `Array.from( context.getNames() ).includes( '$clipboardHolder' )` – it's enough to check the first item or add the `ctx.startsWith()` method.

**Comment by jodator** [comment]
> Do we need the configuration for allowed attributes?

In another way, we will get minor WTF if `bold` is allowed by command and you can bold text inside the non-restricted area but you can't paste it.

But we can also add this configuration later if requested so I can remove this from the PR.

**Comment by jodator** [comment]
@Reinmar: I've added the [`SchemaContext.startsWith()`](https://github.com/ckeditor/ckeditor5-engine/pull/1813) and fixed link attribute name used in default config.

**Comment by Reinmar** [comment]
Lookin' good :candy:!

**Pull request merged**
